# Configuraci贸n de Netlify para la aplicaci贸n de Evaluaci贸n Matrimonial

[build]
  command = "npm run build"
  publish = "dist"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuraci贸n de encabezados para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://matrimoniosrem.com https://flagcdn.com https://images.unsplash.com; connect-src 'self' https://script.google.com https://script.googleusercontent.com;"