import { Question } from './types';

export const questions_en: Question[] = [
  // CONSENSUS
  { id: 1, text: 'I constantly allow rudeness and abuse from my partner', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 2, text: 'I avoid expressing my own opinion when it differs from my partner\'s', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 3, text: 'To avoid problems it\'s better not to say what bothers me', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 4, text: 'I set aside my values and convictions to accept those of my partner', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 5, text: 'We make decisions together as a couple when we go through difficult times', factor: 'CONSENSO', scoring: 'normal' },
  { id: 6, text: 'Instead of what I want, I end up doing what my partner wants', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 7, text: 'I find it difficult to make decisions as a couple', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 8, text: 'I have control over my words and don\'t let my tongue control me', factor: 'CONSENSO', scoring: 'normal' },
  { id: 9, text: 'In my home, finances are managed wisely', factor: 'CONSENSO', scoring: 'normal' },
  { id: 10, text: 'In my relationship, each person manages their own money', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 11, text: 'Both partners have common goals and objectives for the future', factor: 'CONSENSO', scoring: 'normal' },
  { id: 12, text: 'We consult each other before making major expenses', factor: 'CONSENSO', scoring: 'normal' },
  { id: 13, text: 'We agree on how we raise children and set boundaries', factor: 'CONSENSO', scoring: 'normal' },
  { id: 14, text: 'We make important financial decisions, like investments, together', factor: 'CONSENSO', scoring: 'normal' },
  { id: 15, text: 'We support each other in personal projects and activities outside marriage', factor: 'CONSENSO', scoring: 'normal' },
  
  // SATISFACTION
  { id: 16, text: 'We share a similar vision about stress and conflict management', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 17, text: 'We are satisfied with the agreements and commitments we\'ve established in our relationship', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 18, text: 'I feel I\'m pleasing my partner before focusing on myself', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 19, text: 'I appear to be happy even when I feel bad', factor: 'SATISFACCION', scoring: 'reverse' },
  { id: 20, text: 'I know exactly what I expect from my partner', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 21, text: 'I\'m one of those people who pretends everything is going well in the relationship when it\'s not', factor: 'SATISFACCION', scoring: 'reverse' },
  { id: 22, text: 'Overall, I feel satisfied with the communication in my relationship', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 23, text: 'I feel my partner understands and listens to my emotional needs', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 24, text: 'As a couple, we enjoy shared activities and fun times together', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 25, text: 'In my relationship, I can freely express my desires and opinions without fear of negative repercussions', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 26, text: 'I feel my partner supports me in my personal goals and aspirations', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 27, text: 'Our level of intimacy and emotional connection is satisfactory for me', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 28, text: 'I feel valued and respected in my relationship', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 29, text: 'Overall, I feel satisfied with the quality of our life together', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 30, text: 'In my relationship, there are more problems than satisfactions', factor: 'SATISFACCION', scoring: 'reverse' },
  
  // COHESION
  { id: 31, text: 'When a disagreement arises, I\'m usually the one who gives in', factor: 'COHESION', scoring: 'reverse' },
  { id: 32, text: 'I have common interests with my partner', factor: 'COHESION', scoring: 'normal' },
  { id: 33, text: 'In our free time, we almost never do anything together', factor: 'COHESION', scoring: 'reverse' },
  { id: 34, text: 'My partner and I regularly attend church together', factor: 'COHESION', scoring: 'normal' },
  { id: 35, text: 'My partner and I are of the same religion', factor: 'COHESION', scoring: 'normal' },
  { id: 36, text: 'My partner and I often engage in activities or hobbies together', factor: 'COHESION', scoring: 'normal' },
  { id: 37, text: 'I think we have deep and meaningful conversations as a couple frequently', factor: 'COHESION', scoring: 'normal' },
  { id: 38, text: 'I believe there is good emotional communication between me and my partner', factor: 'COHESION', scoring: 'normal' },
  { id: 39, text: 'We spend time together regularly, without distractions', factor: 'COHESION', scoring: 'normal' },
  { id: 40, text: 'I have respect for sexual intimacy in my relationship', factor: 'COHESION', scoring: 'normal' },
  { id: 41, text: 'As a couple, we support each other in our goals, dreams, and responsibilities', factor: 'COHESION', scoring: 'normal' },
  { id: 42, text: 'At home, we resolve conflicts constructively and reach satisfactory agreements', factor: 'COHESION', scoring: 'normal' },
  { id: 43, text: 'I always value my partner\'s strengths and positive qualities', factor: 'COHESION', scoring: 'normal' },
  { id: 44, text: 'I acknowledge when I\'m at fault', factor: 'COHESION', scoring: 'normal' },
  { id: 45, text: 'I feel I no longer have interest in working on the relationship', factor: 'COHESION', scoring: 'reverse' },
  
  // EXPRESSION OF AFFECTION
  { id: 46, text: 'When I need support and love in a situation, I receive it from my partner', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 47, text: 'I recently shared an achievement with my partner', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 48, text: 'I have experienced God\'s grace in my relationship', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 49, text: 'I often avoid expressing my feelings for fear of being criticized', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 50, text: 'I avoid getting angry for fear of losing control', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 51, text: 'It\'s easy for me to say "I love you" to my partner', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 52, text: 'I\'ve always wished I had never gotten married', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 53, text: 'We regularly express physical affection, such as hugs, kisses, or caresses', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 54, text: 'I can openly talk about my emotional needs without fear of judgment or criticism', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 55, text: 'I practice active listening when my partner shares their concerns or problems', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 56, text: 'We face challenges together as a team, supporting each other at all times', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 57, text: 'We express gratitude and appreciation for each other regularly', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 58, text: 'We maintain clear and open communication about our expectations and goals in the relationship', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 59, text: 'We strive to maintain an atmosphere of trust and safety in our relationship', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 60, text: 'We regularly take time to pray together', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  
  // SEXUAL CONNECTION
  { id: 61, text: 'Sexual relations with my partner are satisfactory', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 62, text: 'Having sex with my partner is very important in my life', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 63, text: 'I feel there is monotony in my sexual relations', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 64, text: 'I find my partner sexually attractive', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 65, text: 'I feel ashamed to express my sexual desires', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 66, text: 'I feel my sexual desire has decreased', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 67, text: 'I feel love when I make love with my partner', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 68, text: 'I agree to sex, even when I don\'t want to, to not upset my partner', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 69, text: 'My partner has told me about their sexual fantasies', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 70, text: 'I like the frequency with which I have sex with my partner', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 71, text: 'There is fun in our sexual encounters', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 72, text: 'In my sexual relations there are no distractions', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 73, text: 'I feel sexually attractive to my partner', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 74, text: 'I try to look presentable before being with my partner', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 75, text: 'In my relationship there is a medical problem that prevents me from having sex', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
];