import { Question } from './types';

export const questions_pt: Question[] = [
  // CONSENSO
  { id: 1, text: 'Eu constantemente permito grosserias e abusos do meu parceiro', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 2, text: 'Evito expressar minha própria opinião quando ela é diferente da do meu parceiro', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 3, text: 'Para evitar problemas é melhor não dizer o que me incomoda', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 4, text: 'Deixei de lado meus valores e convicções para aceitar os do meu parceiro', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 5, text: 'Tomamos decisões juntos como casal quando passamos por momentos difíceis', factor: 'CONSENSO', scoring: 'normal' },
  { id: 6, text: 'Ao invés do que eu quero, acabo fazendo o que meu parceiro deseja', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 7, text: 'Acho difícil tomar decisões como casal', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 8, text: 'Eu tenho controle das minhas palavras e não deixo minha língua me controlar', factor: 'CONSENSO', scoring: 'normal' },
  { id: 9, text: 'Na minha casa, as finanças são geridas com sabedoria', factor: 'CONSENSO', scoring: 'normal' },
  { id: 10, text: 'Na minha relação, cada um administra seu dinheiro', factor: 'CONSENSO', scoring: 'reverse' },
  { id: 11, text: 'Ambos os parceiros têm metas e objetivos comuns para o futuro.', factor: 'CONSENSO', scoring: 'normal' },
  { id: 12, text: 'Consultamo-nos uns aos outros antes de fazer grandes despesas.', factor: 'CONSENSO', scoring: 'normal' },
  { id: 13, text: 'Concordamos sobre como criamos os filhos e estabelecemos limites', factor: 'CONSENSO', scoring: 'normal' },
  { id: 14, text: 'Tomamos decisões financeiras importantes, como investimentos, juntos.', factor: 'CONSENSO', scoring: 'normal' },
  { id: 15, text: 'Apoiamo-nos mutuamente em projetos pessoais e atividades fora do casamento', factor: 'CONSENSO', scoring: 'normal' },
  
  // SATISFACCION
  { id: 16, text: 'Partilhamos uma visão semelhante sobre o stress e a gestão de conflitos', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 17, text: 'Estamos satisfeitos com os acordos e compromissos que estabelecemos em nosso relacionamento.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 18, text: 'Sinto que estou agradando meu parceiro antes de me concentrar em mim mesmo', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 19, text: 'Aparento estar feliz, mesmo que me sinta mal', factor: 'SATISFACCION', scoring: 'reverse' },
  { id: 20, text: 'Eu sei exatamente o que espero do meu parceiro.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 21, text: 'Eu sou daquelas pessoas que finge que está tudo indo bem na relação, quando na verdade não está', factor: 'SATISFACCION', scoring: 'reverse' },
  { id: 22, text: 'No geral, me sinto satisfeita com a comunicação no meu relacionamento', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 23, text: 'Sinto que meu parceiro (a) me entende e ouve minhas necessidades emocionais.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 24, text: 'Como casal, desfrutamos de atividades compartilhadas e momentos divertidos juntos.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 25, text: 'No meu relacionamento posso expressar livremente meus desejos e opiniões sem medo de repercussões negativas.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 26, text: 'Sinto que meu parceiro (a) me apoia em meus objetivos e aspirações pessoais.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 27, text: 'Nosso nível de intimidade e conexão emocional é satisfatório para mim.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 28, text: 'Me sinto valorizada (o) e respeitada (o) no meu relacionamento.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 29, text: 'Em geral, me sinto satisfeito com a qualidade da nossa vida a dois.', factor: 'SATISFACCION', scoring: 'normal' },
  { id: 30, text: 'Na minha relação há mais problemas do que satisfações.', factor: 'SATISFACCION', scoring: 'reverse' },
  
  // COHESION
  { id: 31, text: 'Quando surge um desentendimento, geralmente sou eu que cedi', factor: 'COHESION', scoring: 'reverse' },
  { id: 32, text: 'Tenho interesses em comum com o meu parceiro (a)', factor: 'COHESION', scoring: 'normal' },
  { id: 33, text: 'Em nosso tempo livre, quase nunca fazemos nada juntos', factor: 'COHESION', scoring: 'reverse' },
  { id: 34, text: 'Meu parceiro (a) e eu frequentamos regularmente a igreja juntos', factor: 'COHESION', scoring: 'normal' },
  { id: 35, text: 'Meu parceiro e eu somos da mesma religião', factor: 'COHESION', scoring: 'normal' },
  { id: 36, text: 'Meu parceiro (a) e eu frequentemente nos envolvemos em atividades ou hobbies juntos', factor: 'COHESION', scoring: 'normal' },
  { id: 37, text: 'Acho que temos conversas profundas e significativas como casal com frequência', factor: 'COHESION', scoring: 'normal' },
  { id: 38, text: 'Acredito que existe uma boa comunicação emocional entre mim e meu parceiro (a)', factor: 'COHESION', scoring: 'normal' },
  { id: 39, text: 'Passamos tempo juntos regularmente, sem distrações', factor: 'COHESION', scoring: 'normal' },
  { id: 40, text: 'Tenho respeito pela intimidade sexual na minha relação.', factor: 'COHESION', scoring: 'normal' },
  { id: 41, text: 'Como casal, apoiamo-nos mutuamente nos nossos objetivos, sonhos e responsabilidades', factor: 'COHESION', scoring: 'normal' },
  { id: 42, text: 'Em casa, resolvemos conflitos de forma construtiva e chegamos a acordos satisfatórios.', factor: 'COHESION', scoring: 'normal' },
  { id: 43, text: 'Eu sempre valorizo os pontos fortes e as qualidades positivas do meu parceiro.', factor: 'COHESION', scoring: 'normal' },
  { id: 44, text: 'Reconheço quando tenho culpa.', factor: 'COHESION', scoring: 'normal' },
  { id: 45, text: 'Sinto que não tenho mais interesse em trabalhar na relação.', factor: 'COHESION', scoring: 'reverse' },
  
  // EXPRESION DE AFECTO
  { id: 46, text: 'Quando eu preciso de apoio e amor em uma situação, eu recebo do meu parceiro.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 47, text: 'Recentemente, compartilhei uma conquista com meu parceiro (a).', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 48, text: 'Experimentei a graça de Deus em meu relacionamento.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 49, text: 'Costumo evitar expressar meus sentimentos por medo de ser criticado.', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 50, text: 'Evito ficar com raiva por medo de perder o controle.', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 51, text: 'É fácil para mim dizer "eu te amo" para o meu parceiro (a).', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 52, text: 'Eu sempre desejei nunca ter me casado', factor: 'EXPRESION DE AFECTO', scoring: 'reverse' },
  { id: 53, text: 'Expressamos afeto físico regularmente, como abraços, beijos ou carícias.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 54, text: 'Posso falar abertamente sobre minhas necessidades emocionais sem medo de julgamento ou crítica.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 55, text: 'Eu pratico a escuta ativa quando meu parceiro compartilha suas preocupações ou problemas.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 56, text: 'Enfrentamos desafios juntos como uma equipe, apoiando uns aos outros em todos os momentos.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 57, text: 'Expressamos gratidão e apreço uns pelos outros regularmente.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 58, text: 'Mantemos uma comunicação clara e aberta sobre nossas expectativas e objetivos no relacionamento.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 59, text: 'Nós nos esforçamos para manter uma atmosfera de confiança e segurança em nosso relacionamento.', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  { id: 60, text: 'Regularmente dedicamos um tempo para orar juntos', factor: 'EXPRESION DE AFECTO', scoring: 'normal' },
  
  // CONEXION SEXUAL
  { id: 61, text: 'As relações sexuais com meu parceiro são satisfatórias', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 62, text: 'Fazer sexo com meu parceiro (a) é muito importante na minha vida.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 63, text: 'Sinto que nas minhas relações sexuais há monotonia.', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 64, text: 'Eu vejo meu parceiro sexualmente atraente.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 65, text: 'Sinto vergonha de expressar meus desejos sexuais.', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 66, text: 'Sinto que meu desejo sexual diminuiu.', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 67, text: 'Sinto amor quando transo com meu parceiro (a)', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 68, text: 'Concordo em, mesmo que não queira, para não irritar meu parceiro (a)', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
  { id: 69, text: 'Meu parceiro me contou sobre suas fantasias sexuais.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 70, text: 'Gosto da frequência com que transo com meu parceiro.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 71, text: 'Há diversão em nossos encontros sexuais.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 72, text: 'Nas minhas relações sexuais não há distrações.', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 73, text: 'Eu me sinto sexualmente atraente para o meu parceiro (a)', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 74, text: 'Tento estar apresentável antes de com meu parceiro (a)', factor: 'CONEXION SEXUAL', scoring: 'normal' },
  { id: 75, text: 'Na minha relação há um problema médico que me impede de fazer sexo.', factor: 'CONEXION SEXUAL', scoring: 'reverse' },
];